name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Saksham-Goel1107
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg
          snake_color: '#38b000'
          snake_food_color: '#4895ef'
          color_snake_dark: '#38b000'
          color_dots_dark: |
            #2d333b, #394148, #454d56, #4f5964, #596773
          
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
